# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtoid', models.IntegerField(default=0)),
                ('produtonome', models.CharField(max_length=200)),
                ('produtopreco', models.IntegerField(default=0)),
            ],
        ),
    ]
