# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienteid', models.IntegerField(default=0)),
                ('clientenome', models.CharField(max_length=200)),
            ],
        ),
    ]
